package model.Markets;

public enum League {
    NFL, NBA, MLB,
    NHL, NCAAF, NCAAB,
    NCAAWB, WNBA, UFC,
    MLS, FIFACLUBWORLDCUP,
    EPL, BUNDESLIGA, SERIEA,
    LALIGA, LIGUE1, CHAMPIONSLEAGUE,
    EUROPALEAGUE, WTA, ATP, PGA, ENTERTAINMENT;
}
